version: "3.2"

services:
  api:
    build: ./images/api
    ports:
      - 8080:3000
    volumes:
      - ./images/api/src:/usr/app/src
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3000/ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  stores:
    image: mysql:latest
    ports:
      - "3306:3306"
    env_file:
      - .env


