name: Remove Runs

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Remove runs
      run: gh run list -L 50 -s completed -q "workflow:Test" | xargs gh run delete

