name: Test Build Push

on:
  push:
    branches:
      - main

jobs:
  build_test_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Clear Local Images
        run: docker rmi meymey200/portfolio-starter-mey-linmus-api:latest || true

      - name: Set up Docker Compose for Production
        run: docker-compose -f docker-compose.production.yml build

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        run: |
          docker-compose -f docker-compose.production.yml push
          docker push meymey200/portfolio-starter-mey-linmus-api:latest
